import type { EntityNodeData, FlowEdgeData, ScenarioState } from '../types';

const NOW = '2026-09-07T00:00:00.000Z';
const ALL_LAYERS = ['treasury', 'vat', 'tax', 'social', 'legal'] as const;

function scenario(
  partial: Omit<ScenarioState, 'version' | 'createdAt' | 'updatedAt' | 'activeLayers'> & {
    activeLayers?: ScenarioState['activeLayers'];
  },
): ScenarioState {
  return {
    version: 1,
    createdAt: NOW,
    updatedAt: NOW,
    activeLayers: partial.activeLayers ?? [...ALL_LAYERS],
    ...partial,
  };
}

/** Freelance SASU seule: Clients → SASU → Personne / DGFiP / URSSAF. */
export const FREELANCE_SASU_PRESET: ScenarioState = scenario({
  id: 'preset-freelance-sasu',
  name: 'Freelance SASU seule',
  description: 'Clients → SASU → Personne physique, DGFiP, URSSAF (salaire vs dividendes directs).',
  presetId: 'freelance-sasu',
  entities: [
    { id: 'client-1', label: 'Clients', entityType: 'client' },
    {
      id: 'sasu-1',
      label: 'SASU OpCo',
      entityType: 'sasu',
      inputs: { caHt: 120_000, expensesHt: 24_000 },
    },
    { id: 'person-1', label: 'Dirigeant', entityType: 'person' },
    { id: 'vendor-1', label: 'Fournisseurs', entityType: 'vendor' },
    { id: 'urssaf-1', label: 'URSSAF', entityType: 'urssaf' },
    { id: 'dgfip-1', label: 'DGFiP', entityType: 'tax_authority' },
  ] satisfies EntityNodeData[],
  flows: [
    {
      id: 'flow-revenue',
      sourceId: 'client-1',
      targetId: 'sasu-1',
      category: 'revenue',
      label: 'Chiffre d’affaires HT',
      amount: 120_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-expense',
      sourceId: 'sasu-1',
      targetId: 'vendor-1',
      category: 'expense',
      label: 'Charges d’exploitation HT',
      amount: 24_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-salary',
      sourceId: 'sasu-1',
      targetId: 'person-1',
      category: 'salary',
      label: 'Rémunération nette président',
      amount: 36_000,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-social',
      sourceId: 'sasu-1',
      targetId: 'urssaf-1',
      category: 'social_charges',
      label: 'Cotisations URSSAF',
      amount: 0,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-vat',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'vat',
      label: 'TVA nette',
      amount: 0,
      periodicity: 'annual',
      layer: 'vat',
    },
    {
      id: 'flow-is',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'is_tax',
      label: 'Impôt sur les sociétés',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
    {
      id: 'flow-dividend-direct',
      sourceId: 'sasu-1',
      targetId: 'person-1',
      category: 'dividend',
      label: 'Dividendes (PFU)',
      amount: 20_000,
      periodicity: 'annual',
      layer: 'tax',
    },
  ] satisfies FlowEdgeData[],
});

/** SASU + Holding: remontée mère-fille puis PFU dirigeant. */
export const SASU_HOLDING_PRESET: ScenarioState = scenario({
  id: 'preset-sasu-holding',
  name: 'SASU + Holding (mère-fille)',
  description: 'SASU opérationnelle + Holding mère — régime mère-fille puis Flat Tax.',
  presetId: 'sasu-holding',
  entities: [
    { id: 'client-1', label: 'Clients', entityType: 'client' },
    {
      id: 'sasu-1',
      label: 'SASU OpCo',
      entityType: 'sasu',
      inputs: { caHt: 200_000, expensesHt: 40_000 },
      ownershipPercent: 100,
    },
    {
      id: 'holding-1',
      label: 'Holding SAS',
      entityType: 'holding_sas',
      ownershipPercent: 100,
    },
    { id: 'person-1', label: 'Dirigeant / Associé', entityType: 'person' },
    { id: 'vendor-1', label: 'Fournisseurs', entityType: 'vendor' },
    { id: 'urssaf-1', label: 'URSSAF', entityType: 'urssaf' },
    { id: 'dgfip-1', label: 'DGFiP', entityType: 'tax_authority' },
  ] satisfies EntityNodeData[],
  flows: [
    {
      id: 'flow-revenue',
      sourceId: 'client-1',
      targetId: 'sasu-1',
      category: 'revenue',
      label: 'Chiffre d’affaires HT',
      amount: 200_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-expense',
      sourceId: 'sasu-1',
      targetId: 'vendor-1',
      category: 'expense',
      label: 'Charges d’exploitation HT',
      amount: 40_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-mgmt-fees',
      sourceId: 'sasu-1',
      targetId: 'holding-1',
      category: 'management_fees',
      label: 'Management fees',
      amount: 12_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-salary',
      sourceId: 'sasu-1',
      targetId: 'person-1',
      category: 'salary',
      label: 'Rémunération nette président',
      amount: 0,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-social',
      sourceId: 'sasu-1',
      targetId: 'urssaf-1',
      category: 'social_charges',
      label: 'Cotisations URSSAF',
      amount: 0,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-vat',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'vat',
      label: 'TVA nette',
      amount: 0,
      periodicity: 'annual',
      layer: 'vat',
    },
    {
      id: 'flow-is-sasu',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'is_tax',
      label: 'IS SASU',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
    {
      id: 'flow-dividend-sasu-holding',
      sourceId: 'sasu-1',
      targetId: 'holding-1',
      category: 'dividend',
      label: 'Dividendes mère-fille',
      amount: 50_000,
      periodicity: 'annual',
      layer: 'tax',
      legalNoteId: 'mere-fille-art-145',
    },
    {
      id: 'flow-dividend-holding-person',
      sourceId: 'holding-1',
      targetId: 'person-1',
      category: 'dividend',
      label: 'Dividendes Holding → PFU',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
  ] satisfies FlowEdgeData[],
});

/** Groupe complet: SASU + Holding + SCI. */
export const FULL_GROUP_PRESET: ScenarioState = scenario({
  id: 'preset-full-group',
  name: 'Groupe SASU + Holding + SCI',
  description:
    'SASU opérationnelle, Holding (100 % SASU / 99 % SCI), SCI immobilière (loyers intra-groupe).',
  presetId: 'full-group',
  entities: [
    { id: 'client-1', label: 'Clients', entityType: 'client' },
    {
      id: 'sasu-1',
      label: 'SASU OpCo',
      entityType: 'sasu',
      inputs: { caHt: 250_000, expensesHt: 50_000 },
      ownershipPercent: 100,
    },
    {
      id: 'holding-1',
      label: 'Holding SAS',
      entityType: 'holding_sas',
      ownershipPercent: 100,
    },
    {
      id: 'sci-1',
      label: 'SCI IS Immobilière',
      entityType: 'sci_is',
      inputs: {
        rentalIncomeHt: 24_000,
        interestExpenses: 8_000,
        buildingAmortization: 6_000,
        otherCharges: 2_000,
      },
      ownershipPercent: 99,
    },
    { id: 'person-1', label: 'Dirigeant / Associé', entityType: 'person' },
    { id: 'vendor-1', label: 'Fournisseurs', entityType: 'vendor' },
    { id: 'urssaf-1', label: 'URSSAF', entityType: 'urssaf' },
    { id: 'dgfip-1', label: 'DGFiP', entityType: 'tax_authority' },
  ] satisfies EntityNodeData[],
  flows: [
    {
      id: 'flow-revenue',
      sourceId: 'client-1',
      targetId: 'sasu-1',
      category: 'revenue',
      label: 'Chiffre d’affaires HT',
      amount: 250_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-expense',
      sourceId: 'sasu-1',
      targetId: 'vendor-1',
      category: 'expense',
      label: 'Charges d’exploitation HT',
      amount: 50_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-rent',
      sourceId: 'sasu-1',
      targetId: 'sci-1',
      category: 'rent',
      label: 'Loyer SCI',
      amount: 24_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-mgmt-fees',
      sourceId: 'sasu-1',
      targetId: 'holding-1',
      category: 'management_fees',
      label: 'Management fees',
      amount: 15_000,
      periodicity: 'annual',
      layer: 'treasury',
    },
    {
      id: 'flow-salary',
      sourceId: 'sasu-1',
      targetId: 'person-1',
      category: 'salary',
      label: 'Rémunération nette président',
      amount: 48_000,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-social',
      sourceId: 'sasu-1',
      targetId: 'urssaf-1',
      category: 'social_charges',
      label: 'Cotisations URSSAF',
      amount: 0,
      periodicity: 'annual',
      layer: 'social',
    },
    {
      id: 'flow-vat',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'vat',
      label: 'TVA nette',
      amount: 0,
      periodicity: 'annual',
      layer: 'vat',
    },
    {
      id: 'flow-is-sasu',
      sourceId: 'sasu-1',
      targetId: 'dgfip-1',
      category: 'is_tax',
      label: 'IS SASU',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
    {
      id: 'flow-is-sci',
      sourceId: 'sci-1',
      targetId: 'dgfip-1',
      category: 'is_tax',
      label: 'IS SCI',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
    {
      id: 'flow-dividend-sasu-holding',
      sourceId: 'sasu-1',
      targetId: 'holding-1',
      category: 'dividend',
      label: 'Dividendes mère-fille',
      amount: 40_000,
      periodicity: 'annual',
      layer: 'tax',
      legalNoteId: 'mere-fille-art-145',
    },
    {
      id: 'flow-dividend-holding-person',
      sourceId: 'holding-1',
      targetId: 'person-1',
      category: 'dividend',
      label: 'Dividendes Holding → PFU',
      amount: 0,
      periodicity: 'annual',
      layer: 'tax',
    },
  ] satisfies FlowEdgeData[],
});

export const STRUCTURE_PRESETS = [
  FREELANCE_SASU_PRESET,
  SASU_HOLDING_PRESET,
  FULL_GROUP_PRESET,
] as const;
