export {
  calculateCorporateTax,
  calculateDividendTax,
  calculateExecutiveSalary,
  calculateFlatTax,
  calculateMicroEnterprise,
  calculateMotherDaughterDividend,
  calculatePersonalIncomeTax,
  calculateSciIrIncome,
  calculateSciTax,
  calculateTnsContributions,
  calculateTnsDividendSurcharge,
  calculateVAT,
  compareDividendTaxModes,
  findMaxGrossSalaryForTargetTMI,
  roundMoney,
  type CorporateTaxResult,
  type DividendArbitrage,
  type DividendTaxMode,
  type DividendTaxResult,
  type ExecutiveSalaryResult,
  type FiscalProfile,
  type FiscalSituation,
  type FlatTaxResult,
  type MicroEnterpriseResult,
  type MotherDaughterDividendResult,
  type PersonalIncomeTaxResult,
  type SciIrResult,
  type SciTaxResult,
  type TnsContributionsResult,
  type TnsDividendSurchargeResult,
  type VatResult,
} from './calculator';

export {
  CSG_DEDUCTIBLE_POINTS,
  DIVIDEND_BAREME_ALLOWANCE,
  EXECUTIVE_COST_FACTOR_APPROX,
  EXECUTIVE_EMPLOYEE_RATE_APPROX,
  IR_2026_BRACKETS,
  IR_DECOTE_COUPLE_EUR,
  IR_DECOTE_SINGLE_EUR,
  IR_DECOTE_SLOPE,
  IR_EXPENSE_ALLOWANCE_CAP_EUR,
  IR_EXPENSE_ALLOWANCE_FLOOR_EUR,
  IR_EXPENSE_FLAT_10_PCT,
  IS_REDUCED_CA_CEILING_EUR,
  IS_REDUCED_RATE,
  IS_REDUCED_THRESHOLD_EUR,
  IS_STANDARD_RATE,
  MICRO_ALLOWANCE_FLOOR_EUR,
  MICRO_BRACKETS_2026,
  MOTHER_DAUGHTER_MIN_HOLDING_PCT,
  MOTHER_DAUGHTER_QPFC_RATE,
  PFU_IR_RATE,
  PFU_PS_RATE,
  PFU_TOTAL_RATE,
  QUOTIENT_FAMILIAL_CAP_PER_HALF_PART_EUR,
  SALARY_NON_DEDUCTIBLE_CSG_CRDS,
  TNS_DIVIDEND_EXEMPT_CAPITAL_SHARE,
  TNS_SOCIAL_RATE_APPROX,
  URSSAF_BRANCHES_2026,
  URSSAF_EMPLOYEE_RATE_2026,
  URSSAF_EMPLOYER_RATE_2026,
  VAT_STANDARD,
  type MicroBracket,
  type MicroCategory,
  type UrssafBranch,
} from './taxRules';

export {
  categoriesVisibleThrough,
  resolveScenarioGraph,
  type ResolvedEntity,
  type ResolvedFlow,
  type ResolvedScenario,
  type ResolvedScenarioSummary,
  type WhatIfInputs,
} from './graphResolver';

export {
  FORECAST_BLIND_SPOTS,
  forecastScenario,
  type ForecastOptions,
  type ForecastResult,
  type ForecastYear,
} from './forecast';

export {
  DEFAULT_PAYOUT_RATIOS,
  OPTIMIZER_BLIND_SPOTS,
  optimizeRemuneration,
  type OptimizationObjective,
  type OptimizationPoint,
  type OptimizationResult,
  type OptimizeOptions,
} from './optimizer';

export {
  STRUCTURE_BLIND_SPOTS,
  compareStructures,
  type StructureComparison,
  type StructureComparisonInputs,
  type StructureId,
  type StructureOutcome,
} from './structureComparator';

export {
  TIMELINE_STEPS,
  getTimelineSteps,
  timelineStepIdForCategory,
  timelineStepOrder,
  type TimelineStep,
  type TimelineStepId,
} from './timelineEngine';
