export {
  calculateCorporateTax,
  calculateDividendTax,
  calculateExecutiveSalary,
  calculateFlatTax,
  calculateMicroEnterprise,
  calculateMotherDaughterDividend,
  calculatePersonalIncomeTax,
  calculateSciIrIncome,
  calculateSciTax,
  calculateTnsContributions,
  calculateTnsDividendSurcharge,
  tnsGrossForNet,
  calculateVAT,
  annualisedRevenue,
  calculateCdhr,
  calculateCharasseReintegration,
  calculateGiftTax,
  calculateHoldingAssetTax,
  calculateMecenat,
  calculatePerDeduction,
  calculatePropertyGain,
  propertyAllowanceIncomeTax,
  propertyAllowanceSocialLevies,
  propertySurtax,
  calculateIfi,
  calculateShareSaleTaxCompany,
  calculateShareSaleTaxPerson,
  cappedRentalAmortization,
  compareDividendTaxModes,
  imputeCarriedDeficit,
  isProfessionalFurnishedRental,
  lateInterest,
  loanAnnuity,
  loanInstallment,
  loanSchedule,
  reducedRateThresholdFor,
  usufructShare,
  bareOwnershipShare,
  findMaxGrossSalaryForTargetTMI,
  roundMoney,
  FULL_EXERCISE_DAYS,
  type CorporateTaxResult,
  type DividendArbitrage,
  type DividendTaxMode,
  type DividendTaxResult,
  type ExecutiveSalaryResult,
  type FiscalProfile,
  type FiscalSituation,
  type FlatTaxResult,
  type MicroEnterpriseResult,
  type MotherDaughterDividendResult,
  type PersonalIncomeTaxResult,
  type SciIrResult,
  type SciTaxResult,
  type TnsContributionsResult,
  type TnsDividendSurchargeResult,
  type VatResult,
  type DeficitImputation,
  type GiftOptions,
  type GiftTaxResult,
  type IfiResult,
  type LoanInstallment,
  type LoanKind,
  type LoanTerms,
  type RentalAmortizationResult,
  type ShareSaleCompanyResult,
  type ShareSalePersonOptions,
  type ShareSaleTaxResult,
  type CdhrResult,
  type CharasseResult,
  type HoldingAssetTaxResult,
  type MecenatResult,
  type PerDeductionResult,
  type PropertyGainOptions,
  type PropertyGainResult,
} from './calculator';

export {
  CSG_DEDUCTIBLE_POINTS,
  DIVIDEND_BAREME_ALLOWANCE,
  IR_2026_BRACKETS,
  IR_DECOTE_COUPLE_EUR,
  IR_DECOTE_SINGLE_EUR,
  IR_DECOTE_SLOPE,
  IR_EXPENSE_ALLOWANCE_CAP_EUR,
  IR_EXPENSE_ALLOWANCE_FLOOR_EUR,
  IR_EXPENSE_FLAT_10_PCT,
  ACRE_MICRO_REDUCTION,
  CCA_INTEREST_CAP_RATE,
  MICRO_VERSEMENT_LIBERATOIRE_RATES,
  VAT_FRANCHISE_CEILING_GOODS_EUR,
  VAT_FRANCHISE_CEILING_SERVICES_EUR,
  INTEGRATED_GROUP_MIN_HOLDING_PCT,
  INTEGRATED_GROUP_QPFC_RATE,
  IS_REDUCED_CA_CEILING_EUR,
  IS_REDUCED_RATE,
  IS_REDUCED_THRESHOLD_EUR,
  IS_STANDARD_RATE,
  MICRO_ALLOWANCE_FLOOR_EUR,
  MICRO_BRACKETS_2026,
  MOTHER_DAUGHTER_MIN_HOLDING_PCT,
  MOTHER_DAUGHTER_QPFC_RATE,
  PFU_IR_RATE,
  PFU_PS_RATE,
  PS_CAPITAL_DEROGATORY_RATE,
  PFU_TOTAL_RATE,
  QUOTIENT_FAMILIAL_CAP_PER_HALF_PART_EUR,
  SALARY_NON_DEDUCTIBLE_CSG_CRDS,
  TNS_DIVIDEND_EXEMPT_CAPITAL_SHARE,
  URSSAF_BRANCHES_2026,
  URSSAF_EMPLOYEE_RATE_2026,
  URSSAF_EMPLOYER_RATE_2026,
  VAT_STANDARD,
  ANIMATRICE_EVIDENCE,
  DEFICIT_CARRYFORWARD_CAP_EUR,
  DEFICIT_CARRYFORWARD_MARGINAL_SHARE,
  DEFICIT_FONCIER_GLOBAL_CAP_EUR,
  DEFICIT_GLOBAL_CARRY_YEARS,
  DMTG_ABATEMENT_RENEWAL_YEARS,
  DMTG_DIRECT_LINE_ABATEMENT_EUR,
  DMTG_DIRECT_LINE_BRACKETS,
  DUTREIL_COLLECTIVE_YEARS,
  DUTREIL_EXEMPTION_RATE,
  DUTREIL_INDIVIDUAL_YEARS,
  IFI_BRACKETS,
  IFI_DECOTE_BASE_EUR,
  IFI_DECOTE_SLOPE,
  IFI_THRESHOLD_EUR,
  LATE_INTEREST_MONTHLY_RATE,
  LMNP_DEFICIT_CARRY_YEARS,
  LMP_RECEIPTS_THRESHOLD_EUR,
  PARTICIPATION_MIN_HOLDING_PCT,
  PARTICIPATION_MIN_HOLDING_YEARS,
  PARTICIPATION_QPFC_RATE,
  REPORT_CONTROL_PRESUMPTION_PCT,
  REPORT_DONATION_PURGE_YEARS,
  REPORT_DONATION_PURGE_YEARS_FUND,
  REPORT_REINVESTMENT_HOLDING_YEARS,
  REPORT_REINVESTMENT_QUOTA,
  REPORT_REINVESTMENT_WINDOW_YEARS,
  REPORT_SALE_WINDOW_YEARS,
  RETIREMENT_FIXED_ALLOWANCE_EUR,
  SHARE_SALE_ALLOWANCE_2_TO_8,
  SHARE_SALE_ALLOWANCE_ACQUISITION_CUTOFF_YEAR,
  SHARE_SALE_ALLOWANCE_OVER_8,
  USUFRUIT_TEMPORAIRE_SHARE_PER_DECADE,
  USUFRUIT_VIAGER_BAREME,
  CDHR_ALLOWANCE_COUPLE_EUR,
  CDHR_ALLOWANCE_PER_DEPENDENT_EUR,
  CDHR_RATE,
  CDHR_SMOOTHING_CEILING_COUPLE_EUR,
  CDHR_SMOOTHING_CEILING_SINGLE_EUR,
  CDHR_SMOOTHING_SLOPE,
  CDHR_THRESHOLD_COUPLE_EUR,
  CDHR_THRESHOLD_SINGLE_EUR,
  CHARASSE_REINTEGRATION_YEARS,
  HOLDING_ASSET_TAX_CONTROL_PCT,
  HOLDING_ASSET_TAX_PASSIVE_SHARE,
  HOLDING_ASSET_TAX_RATE,
  HOLDING_ASSET_TAX_THRESHOLD_EUR,
  MECENAT_CAP_FLOOR_EUR,
  MECENAT_CAP_REVENUE_SHARE,
  MECENAT_CARRY_YEARS,
  MECENAT_RATE,
  MECENAT_RATE_ABOVE_THRESHOLD,
  MECENAT_RATE_THRESHOLD_EUR,
  PER_CARRY_YEARS,
  PER_DEDUCTION_RATE,
  PER_INCOME_CAP_PASS,
  PROPERTY_ACQUISITION_COSTS_FLAT,
  PROPERTY_ALLOWANCE_IR_PER_YEAR,
  PROPERTY_ALLOWANCE_IR_YEAR_22,
  PROPERTY_ALLOWANCE_PS_BEYOND_22,
  PROPERTY_ALLOWANCE_PS_PER_YEAR,
  PROPERTY_ALLOWANCE_PS_YEAR_22,
  PROPERTY_GAIN_IR_RATE,
  PROPERTY_SMALL_SALE_EXEMPTION_EUR,
  PROPERTY_SURTAX_BRACKETS,
  PROPERTY_WORKS_FLAT,
  PROPERTY_WORKS_FLAT_MIN_YEARS,
  type PropertySurtaxBracket,
  type MicroBracket,
  type MicroCategory,
  type UrssafBranch,
} from './taxRules';

export {
  categoriesVisibleThrough,
  emptyCarryOver,
  resolveScenarioGraph,
  type AssetSchedule,
  type CarryOver,
  type DeferredGain,
  type DeficitStock,
  type LoanState,
  type ResolvedEntity,
  type ResolvedFlow,
  type ResolvedScenario,
  type ResolvedScenarioSummary,
  type WhatIfInputs,
} from './graphResolver';

export { parseWhatIfInputs, whatIfInputsSchema } from './whatIfSchema';

export {
  FORECAST_BLIND_SPOTS,
  forecastScenario,
  type ForecastOptions,
  type ForecastResult,
  type ForecastYear,
} from './forecast';

export {
  DEFAULT_PAYOUT_RATIOS,
  OPTIMIZER_BLIND_SPOTS,
  optimizeRemuneration,
  type OptimizationObjective,
  type OptimizationPoint,
  type OptimizationResult,
  type OptimizeOptions,
} from './optimizer';

export {
  STRUCTURE_BLIND_SPOTS,
  compareStructures,
  type StructureComparison,
  type StructureComparisonInputs,
  type StructureId,
  type StructureOutcome,
} from './structureComparator';

export {
  TIMELINE_STEPS,
  getTimelineSteps,
  timelineStepIdForCategory,
  timelineStepOrder,
  type TimelineStep,
  type TimelineStepId,
} from './timelineEngine';

export * from './tnsRules';
